; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and example
; https://docs.platformio.org/page/projectconf.html

[platformio]

; default_envs = Arduino_GFX_PDQgraphicstest
; default_envs = Arduino_GFXDemo
; default_envs = factory
; default_envs = Sleep
; default_envs = lv_demos
; default_envs = nes
; default_envs = sd
; default_envs = tft
; default_envs = TFT_Rainbow
; default_envs = touch_test
; default_envs = usb_hid_pad
; default_envs = ota
; default_envs = SerialExample
; default_envs = T-Display-S3-MIDI
; default_envs = T-Display-S3-Piano
; default_envs = ImageScroll
; default_envs = GetBatteryVoltage
default_envs = sd
; default_envs = PCBClock
; default_envs = WIFI_Audio_I2S
; default_envs = CapacitiveTouch

src_dir = src

boards_dir = ./boards

[env]
platform = espressif32@6.5.0
board = lilygo-t-displays3
framework = arduino

debug_tool = esp-builtin

; Use this when burning with USB CDC
upload_protocol = esptool

; When using ESP32-USB-JTAG debugging
; upload_protocol = esp-builtin

build_flags = 
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; -UARDUINO_USB_CDC_ON_BOOT
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DARDUINO_USB_MODE=1
    ; Choose different options according to different driver chips
    ; Early use of CST328
    -DTOUCH_MODULES_CST_MUTUAL
    ; Use CST816 by default
    ; -DTOUCH_MODULES_CST_SELF        

[env:sd]
lib_deps =
    bodmer/TFT_eSPI
build_flags =
    ${env.build_flags}
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DINIT_SEQUENCE_3=1
    -DCGRAM_OFFSET=1
    -DTFT_RGB_ORDER=TFT_RGB
    -DTFT_INVERSION_ON=1
    -DTFT_PARALLEL_8_BIT=1
    -DTFT_WIDTH=170
    -DTFT_HEIGHT=320
    -DTFT_BL=38
    -DTFT_BACKLIGHT_ON=HIGH
    -DTFT_CS=6
    -DTFT_DC=7
    -DTFT_RST=5
    -DTFT_WR=8
    -DTFT_RD=9
    -DTFT_D0=39
    -DTFT_D1=40
    -DTFT_D2=41
    -DTFT_D3=42
    -DTFT_D4=45
    -DTFT_D5=46
    -DTFT_D6=47
    -DTFT_D7=48
    -DSPI_FREQUENCY=80000000
    -DSMOOTH_FONT=1
lib_ignore =
    GFX Library for Arduino
    arduino-nofrendo
    Adafruit MPR121
    DabbleESP32
    PCF8575 library
    PCA95x5
    lvgl

[env:Sleep]
lib_ignore =
    GFX Library for Arduino
    arduino-nofrendo
    Adafruit MPR121
    DabbleESP32
    PCF8575 library
    PCA95x5
    lvgl

[env:PokerS3]

lib_deps =
    bodmer/TFT_eSPI
build_flags =
    ${env.build_flags}
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DINIT_SEQUENCE_3=1
    -DCGRAM_OFFSET=1
    -DTFT_RGB_ORDER=TFT_RGB
    -DTFT_INVERSION_ON=1
    -DTFT_PARALLEL_8_BIT=1
    -DTFT_WIDTH=170
    -DTFT_HEIGHT=320
    -DTFT_BL=38
    -DTFT_BACKLIGHT_ON=HIGH
    -DTFT_CS=6
    -DTFT_DC=7
    -DTFT_RST=5
    -DTFT_WR=8
    -DTFT_RD=9
    -DTFT_D0=39
    -DTFT_D1=40
    -DTFT_D2=41
    -DTFT_D3=42
    -DTFT_D4=45
    -DTFT_D5=46
    -DTFT_D6=47
    -DTFT_D7=48
    -DSPI_FREQUENCY=80000000
    -DSMOOTH_FONT=1
lib_ignore =
    GFX Library for Arduino
    arduino-nofrendo
    Adafruit MPR121
    DabbleESP32
    PCF8575 library
    PCA95x5
    lvgl
